version: '3.6'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fermat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: